### ISSUE TITLE
Remind me of the difference between the data files? 

### ISSUE THREAD

**Issue by RuthAngus** [RuthAngus/flicker#2]
What is the difference between the flickers.dat & the log.dat data files and the BIGDATA files again?

(I know you've told me this many times, but I keep forgetting!)

**Comment by davidkipping** [comment]
No problem!

You should use the "filtered" files only. They exclude Teff's and other terms which exceeds the pre-defined range over which flicker is deemed to work well by Bastien et al.

Out of the two, the nohuber one simply excludes the Huber data, as the name suggests. You should use nohuber for the logg correlation and the full data set when doing the rho\* calibration.
